### ISSUE TITLE
Webpage is unfunctional

### ISSUE THREAD

**Issue by MudaVunts** [cryptNG/genuine-captcha#1]
Hello, was curious about your project and visited your website. The page was not very user-friendly.
Added a Testcase file. Since I'm a beginner Tester, all feedback on Testcase is welcome.
[Test case Genuine Captcha.xlsx](https://github.com/cryptNG/genuine-captcha/files/13972083/Test.case.Genuine.Captcha.xlsx)

**Comment by ChristianGreinke** [comment]
Thanks for highlighting. Website is functional again :-)
